apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-helloworld
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: demo-nodejs
        image: mk912/template_nodejs:v1
        ports:
        - name: port-helloworld
          containerPort: 3000
      nodeSelector:
        hardware: high-spec
