apiVersion: v1
kind: Service
metadata:
  name: svc-helloworld
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: port-helloworld
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
